export { Main } from './Main/Main'
export { Register } from './Register/Register'
export { SignIn } from './SignIn/SignIn'
export {ResetPassword} from './ResetPassword/ResetPassword'
export {ForgotPassword} from './ForgotPassword/ForgotPassword'
export {NotFound} from './NotFound/NotFound'
export {Profile} from './Profile/Profile'