export enum constructorActions {
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',
    RESET_INGREDIENTS = 'RESET_INGREDIENTS',
    ADD_INGREDIENTS_TO_CONSTRUCTOR = 'ADD_INGREDIENTS_TO_CONSTRUCTOR',
    MOVE_CARD = 'MOVE_CARD',
}
