export enum wsFeedActions {
  FEED_CONNECTION_START = 'FEED_CONNECTION_START',
  FEED_CONNECTION_STOP = 'FEED_CONNECTION_STOP',
  FEED_CONNECTION_SUCCESS = 'FEED_CONNECTION_SUCCESS',
  FEED_CONNECTION_ERROR = 'FEED_CONNECTION_ERROR',
  FEED_CONNECTION_CLOSED = 'FEED_CONNECTION_CLOSED',
  FEED_SEND_MESSAGE = 'FEED_SEND_MESSAGE',
  FEED_GET_MESSAGE = 'FEED_GET_MESSAGE',
}
