export enum wsProfileActions {
  PROFILE_CONNECTION_START = 'PROFILE_CONNECTION_START',
  PROFILE_CONNECTION_STOP = 'PROFILE_CONNECTION_STOP',
  PROFILE_CONNECTION_SUCCESS = 'PROFILE_CONNECTION_SUCCESS',
  PROFILE_CONNECTION_ERROR = 'PROFILE_CONNECTION_ERROR',
  PROFILE_CONNECTION_CLOSED = 'PROFILE_CONNECTION_CLOSED',
  PROFILE_SEND_MESSAGE = 'PROFILE_SEND_MESSAGE',
  PROFILE_GET_MESSAGE = 'PROFILE_GET_MESSAGE',
}
